ZDOTDIR="$HOME/.config/zsh"
SPACESHIP_CONFIG="$ZDOTDIR/spaceship.zsh"
SPACESHIP_ASYNC_SHOW=false
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_DIR_TRUNC=5

# export SPACESHIP_PACKAGE_SHOW=false
# export SPACESHIP_KUBECTL_SHOW=true
# export SPACESHIP_KUBECTL_VERSION_SHOW=false
# export SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE=false
# export SPACESHIP_KUBECTL_SYMBOL="☸️ "
# export SPACESHIP_GCLOUD_SHOW=false
# export SPACESHIP_PHP_SHOW=false

