export ZDOTDIR="$HOME/.config/zsh"

export SPACESHIP_PACKAGE_SHOW=false
export SPACESHIP_KUBECTL_SHOW=true
export SPACESHIP_KUBECTL_VERSION_SHOW=false
export SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE=false
export SPACESHIP_KUBECTL_SYMBOL="☸️ "
export SPACESHIP_DIR_TRUNC=5
export SPACESHIP_GCLOUD_SHOW=false
export SPACESHIP_PHP_SHOW=false

export ZSH_DOTENV_PROMPT=false

export NVM_COMPLETION=true
export NVM_AUTO_USE=true
# NVM_LAZY_LOAD=true
# NVM_LAZY_LOAD_EXTRA_COMMANDS=('pnpm' 'yarn')

