#!/bin/bash

set -eu

BOOTSTRAP_D="$0.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    err "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

source $BOOTSTRAP_D/base/install-zx.sh

$BOOTSTRAP_D/index.mjs
