[[items]]
template = "wezterm"
file = "~/.config/wezterm/colors/flavours.toml"
rewrite = true

[[items]]
template = "neovim"
file = "~/.config/nvim/colors/flavours.lua"
rewrite = true

[[items]]
template = "nushell"
file = "~/.config/nushell/scripts/plugins/theme.nu"
rewrite = true

# [[items]]
# template = "vscode"
# file = "~/.config/Code - OSS/User/test-theme.json"
# rewrite = true
