schemes = "https://github.com/Softsun2/base16-schemes-source"
templates = "https://github.com/chriskempson/base16-templates-source"
# schemes = "https://github.com/Base24/base24-schemes-source"
# templates = "https://github.com/Base24/base24-templates-source"

[[items]]
template = "wezterm"
file = "~/.config/wezterm/colors/flavours.toml"
rewrite = true

[[items]]
template = "neovim"
file = "~/.config/nvim/colors/flavours.lua"
rewrite = true

[[items]]
template = "neovim"
file = "~/.config/lvim/colors/flavours.lua"
rewrite = true

[[items]]
template = "nushell"
file = "$XDG_CACHE_HOME/nu/theme.nu"
rewrite = true

[[items]]
template = "vivid"
file = "~/.config/vivid/themes/flavours.yml"
rewrite = true

[[items]]
template = "btop"
file = "~/.config/btop/themes/flavours.theme"
rewrite = true

