#!/bin/bash

find_all_up() {
    local -a FILES=()
    local TARGET=${1:-.envrc}
    cd ..
    while true; do
        if [[ -f $TARGET ]]; then
            FILES+=("$PWD/$TARGET")
        fi
        if [[ $PWD == / ]] || [[ $PWD == // ]] || [[ $PWD == $HOME ]]; then
            break
        fi
        cd ..
    done

    printf '%s\n' "${FILES[@]}" | tac
}

source_all_up() {
    local UP_FILES=$(find_all_up "$@")

    for f in ${UP_FILES[@]}; do
        source_env $f
    done
}

layout_laravel() {
    layout php

    lib_dir="$(direnv_layout_dir)/laravel_sail"
    bin_dir="$lib_dir/bin"
    mkdir -p "$bin_dir"
    local scripts=(
        composer
        artisan
        php
        tinker
    )
    for script in ${scripts[@]}; do
        echo "sail $script \$@" > $bin_dir/$script
    done
    chmod -R u+x $bin_dir
    PATH_add "$bin_dir"
}

source_all_up
use asdf
