#!/bin/bash

DIRENV_TMP_DIR="${PWD}/.direnv"
DIRENV_BIN_DIR="${DIRENV_TMP_DIR}/bin"

[ ! -e "${DIRENV_BIN_DIR}" ] && mkdir -p "${DIRENV_BIN_DIR}"
PATH_add $DIRENV_BIN_DIR

layout_laravel_sail() {
    layout php
    local scripts=(composer artisan php)
    for script in ${scripts[@]}; do
        echo "sail $script \$@" > $DIRENV_BIN_DIR/$script
    done
    chmod -R u+x $DIRENV_BIN_DIR
}

