# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = '[:::](bright-black) '

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold blue)"

[aws]
disabled = true

[directory]
truncation_length = 5

[php]
format = 'via [$symbol]($style)'

[python]
format = 'via [${symbol}${pyenv_prefix}(${version})]($style) '

[status]
disabled = false
symbol = '✘'

[shell]
disabled = false
nu_indicator = ""
format = "([$indicator](style) )"
